### ISSUE TITLE
S7-1200大批量短间隔读取性能如何啊？

### ISSUE THREAD

**Issue by diamondboy** [dathlin/HslCommunication#1]
首先谢谢你提供的这个库，实在太好用了。
我要读S7-1200的DB块数据，大概1W个点，要求至少5秒刷新，性能有保障么？

**Comment by dathlin** [comment]
如果1W个点数据都在连续的数据块，那么可以达到100ms刷新，性能上肯定有保障

**Comment by dathlin** [comment]
close
