### ISSUE TITLE
三菱模组断线判断

### ISSUE THREAD

**Issue by ghostx2** [dathlin/HslCommunication#15]
使用三菱模组时，因现场环境会有断线可能，虽然HslCommunication有重连机制，但我要怎样更即时判断是否已断线？目前测式来看Connect Failed、Receive data timeout的error code都是10000，是否所有关于Socket类的错误我都直接用10000来判断？感谢

**Comment by dathlin** [comment]
判断通信是否成功使用IsSuccess来判断，如果您想即时的判断是否断线，此处推荐3方法：
1. ReceiveTimeout设置为1000，你的server如果本身不停的读写设备数据的话，可以判断IsSuccess来判断是否掉线了。
2. 你开辟一个新的线程，来读取某个特殊的地址的数据，如果IsSuccess=False，就是掉线了，
3. 你开辟一个新的线程来ping设备，不同了就是设备掉线了。
