### ISSUE TITLE
批量读取smart200数据异常  读取如M1.4值返回永远是0

### ISSUE THREAD

**Issue by get008** [dathlin/HslCommunication#17]
string[] addr = { "V1064", "M1.4", "Q0.1" };
 ushort[] cnt = { 4, 1 ,1};
 string[] resltVal = new string[] {" " ," "};
 var result = siemensTcpNet.Read(addr, cnt);
      result返回值中M1.4 Q0,1 值不正确永远是0  通过ReadBool读取正确

**Comment by dathlin** [comment]
读单个的地址只能使用 ReadBool
如果你想批量读，只能读字
string[] addr = { "V106", "M1", "Q0" };
ushort[] cnt = { 4, 1 ,1};
string[] resltVal = new string[] {" " ," "};
var result = siemensTcpNet.Read(addr, cnt);

然后解析数据，分析出你的实际的数据内容。

**Comment by get008** [comment]
这样也行 
但是我选择修改源码BuildReadCommand 在批量读取遇到如M1.4值时将  
// 按字为单位 -> by word
 _PLCCommand[22 + ii * 12] = 0x02;改为 _PLCCommand[22 + ii * 12] = 0x01;
并在Read 函数中将if (read.Content[ii] == 0xFF && read.Content[ii + 1] == 0x04）改为
 if (read.Content[ii] == 0xFF &&(read.Content[ii + 1] == 0x04 || read.Content[ii + 1] == 0x03))
这样解决
