### ISSUE TITLE
Demo: link is returnning page not found

### ISSUE THREAD

**Issue by arunpratap26** [dathlin/HslCommunication#2]
https://github.com/dathlin/HslCommunicationDemo This link is not working

**Comment by dathlin** [comment]
demo is in current project . thank you

**Comment by arunpratap26** [comment]
@dathlin you need to edit demo link that you have written in readme.md that is not working

**Comment by dathlin** [comment]
yes

**Comment by arunpratap26** [comment]
i have just  made a pull request with that
