### ISSUE TITLE
read方法批量读取西门子1500DB块的值，当长度超出时，返回成功但实际没有读到

### ISSUE THREAD

**Issue by LiuFu2014** [dathlin/HslCommunication#20]
如果读写语句：
`SiemensTcpNet.Read("DB101.0", 70)`
参数值70如果超出了设定的DB块字节数，那么就读不到值，全部返回0，此时，操作结果类返回的是success，应该返回false才对；

**Comment by dathlin** [comment]
是有这个问题，我也发现了，我先思考下解决方法。

**Comment by dathlin** [comment]
终于修复这个bug了，最新版 v6.2.5感谢。

**Comment by LiuFu2014** [comment]
厉害厉害，能参与bug提交我感到很荣幸哈~
