### ISSUE TITLE
5.7.1三菱模组出现数据超时，无法读取数据(使用MC-Qna-1E协议)

### ISSUE THREAD

**Issue by yuta2** [dathlin/HslCommunication#22]
5.7.1三菱模组出现数据超时，无法读取数据(使用MC-Qna-1E协议)
使用旧版5.6.2则正常。(5.6.2-5.7.0中间的版本没测试)
![2019-01-09_18-28-30](https://user-images.githubusercontent.com/9444104/50894710-e4c2a480-143e-11e9-93ad-e85c4c9d89ee.png)

**Comment by dathlin** [comment]
收到，我这边简单的测试了下，5.7.1读取L02的PLC是正常的，无论是M点位数据，D点位数据，都是支持读写的，你这边的问题还需要详细确认细节。

**Comment by yuta2** [comment]
我试试能不能找出LOG，不过我测试了几个版本，5.6.0 读写上述相同一台PLC立刻有回应，5.6.2约3秒钟才有回应，5.7.0读写约1秒有回应，5.7.1逾时错误. 有其他资讯我再提供上来。

**Comment by dathlin** [comment]
@btl1817 请联系我下，帮忙测试下新的demo，5.7.1在读取位数据上支持按照字读取，我还没有进行仔细的测试。

**Comment by dathlin** [comment]
@yuta2 @btl1817 v5.7.2已经修复问题，感谢测试。
