### ISSUE TITLE
C++ use cases?

### ISSUE THREAD

**Issue by kumar10725** [dathlin/HslCommunication#25]
I am working on Mitsubishi PLCs. I really think your library is very useful. Good work. I have tried to use the dlls provided by you in c# and it's works seamlessly. 

However I have been trying to implement your drivers in c++. I saw that you have c++ examples in your documentation but however, I cannot find a way to import your dll files c++ (visual studio). Could you please show me how to use your dll in c++ environment?
i already included your dll files in the linker input section. and when using namespace and using "hslcommunication.dll" function but the visual studio gives an error when define a function. I am using c++/cli.
Any help would be very appreciated. Thank you.

**Comment by dathlin** [comment]
sorry , I didn't try to call the DLL in C + +, but I had a friend who tested successfully and I asked him to answer the question.

**Comment by dathlin** [comment]
I'll upload another example of the code tomorrow, it's 10 o'clock in the evening. Just a little, wait, thank you for trusting this component.

**Comment by kumar10725** [comment]
Thank you for such a quick response. It's a fantastic components, you've made. Keep up the good work.

**Comment by dathlin** [comment]
[HslCppDemo.zip](https://github.com/dathlin/HslCommunication/files/2969780/HslCppDemo.zip)
This is the demo, u can try and test it

**Comment by dathlin** [comment]
https://github.com/dathlin/HslCommunication/tree/master/TestProject/HslCommunicationCppDemo

I have add a cpp project that use the hsl.dll，with test modbus server. thank you for test

**Comment by kumar10725** [comment]
Thank you so much for your quick help. I will try it and then put a feedback here. Again it's a great component you have developed. It will help a lot of automation engineers.

**Comment by kumar10725** [comment]
The test program works perfectly in mfc/afx application.
But when I try to implement same function in CLR application with UI. The program gives an error during debug x64. One of the dependencies of hslCommunication.dll could not be loaded. 
What could be the reason for this?
