### ISSUE TITLE
I wanted to add plc ls to your libraries

### ISSUE THREAD

**Issue by AbdalaMask** [dathlin/HslCommunication#31]
I wanted to add plc ls to your libraries

I want a way to connect PLC LS The connection protocol is two types
CNET

FENET
Link PLC
http://www.lsis.com/product/depth2.aspx?d1=CCC&d2=001
And

http://www.lsis.com/product/product.aspx?d1=CCC&c=P00139

**Comment by dathlin** [comment]
sorry, I am not familiar with this plc, I can not debug the program, but I very much welcome you to develop the communication class, added to the HSL inside.

**Comment by AbdalaMask** [comment]
ok
I am designed alone to communicate

link
https://github.com/AbdalaMask/LSIS.Core

**Comment by AbdalaMask** [comment]
PLC LS in Korea

**Comment by dathlin** [comment]
i know, If you have a detailed communication manual, I can also come to develop it.

**Comment by AbdalaMask** [comment]
ok
link Cnet 
http://www.lsis.com/support/download/detail.aspx?c=3153

Chapter 7 XGT Dedicated Protocol
number 93
link Fnet
 XGB Fast Ethernet I/F Module(XBL-EMTA) User's Manual
http://www.lsis.com/support/download/detail.aspx?c=3152
5.2 XGT Dedicated Protocol

number 30 

Do you have a Facebook account? I communicate with you
Thanks for contacting me

**Comment by dathlin** [comment]
sorry , i can't access facebook from china, you can contact me from here:
https://gitter.im/HslCommunication/community
if i see  it, i will reply u
