### ISSUE TITLE
布尔类型无法写入

### ISSUE THREAD

**Issue by MakitaToki** [dathlin/HslCommunication#32]
S7-200 Smart中布尔类型地址格式是`存储器[字节地址].[位地址]`，比如M0.0，报告如下错误。
![image](https://user-images.githubusercontent.com/42334057/194710893-e18f8686-2a26-44df-b2b3-281bdff55e9c.png)

**Comment by dathlin** [comment]
值里面写 True  或是 False

**Comment by MakitaToki** [comment]
谢谢作者开发的软件，体验很好
