### ISSUE TITLE
能支持循环读，循环写么？

### ISSUE THREAD

**Issue by Craze5** [dathlin/HslCommunication#33]
![image](https://user-images.githubusercontent.com/16759471/194800542-08a49236-37d5-4c5d-b7f3-99eb4a22fcb1.png)

![image](https://user-images.githubusercontent.com/16759471/194800633-a76a98ab-34b1-439d-bb40-225755f291a5.png)

![image](https://user-images.githubusercontent.com/16759471/194800766-b26886db-075d-454f-bb8f-ee727ab801fe.png)

**Comment by dathlin** [comment]
当然支持循环读，循环写了，只是你这业务代码，我也看不出来是否有问题
