### ISSUE TITLE
西门子字符串 读到历史值怎么处理

### ISSUE THREAD

**Issue by Craze5** [dathlin/HslCommunication#39]
西门子字符串 读到历史值怎么处理

**Comment by dathlin** [comment]
不太明白，读到历史值是什么意思

**Comment by Craze5** [comment]
![image](https://user-images.githubusercontent.com/16759471/232361428-9cf59de2-3f72-469e-9a56-7d317255e924.png)

**Comment by Craze5** [comment]
怎么拿实际值？ 有方法么

**Comment by Craze5** [comment]
![image](https://user-images.githubusercontent.com/16759471/232368921-2f2c5101-4e66-4dae-abcc-2b217707246c.png)

随便写了一个，不知道hsl 里面有没有自带

**Comment by dathlin** [comment]
在hsl里有自带的，例如你得字符串存储在 DB1.0  里面，那么可以直接调用下面的方法

`
OperateResult<string> read = plc.ReadString("DB1.0");
if (read.IsSuccess)
{
     string value = read.Content;
}
`

**Comment by Craze5** [comment]
不写长度就是得？

**Comment by Craze5** [comment]
> 在hsl里有自带的，例如你得字符串存储在 DB1.0 里面，那么可以直接调用下面的方法
> 
> `OperateResult<string> read = plc.ReadString("DB1.0"); if (read.IsSuccess) { string value = read.Content; }`

不行，必须输入长度，西门子PLC，开始两个字符是 总长度与有效长度，得转

**Comment by Craze5** [comment]
![image](https://user-images.githubusercontent.com/16759471/232379951-18f34731-f91b-4dac-861a-e414d45df99f.png)
![image](https://user-images.githubusercontent.com/16759471/232380114-99ac6540-71f8-476b-b023-685e774b0501.png)

![image](https://user-images.githubusercontent.com/16759471/232380611-c13b2c23-63f5-41ee-8840-0818ac8a82ac.png)

**Comment by dathlin** [comment]
最新版不需要输入，内部自动分析字符串长度的，或是传0也可以。

如果你用的特别老的版本，则可能不行
