### ISSUE TITLE
hi modbus tcp eroor to write

### ISSUE THREAD

**Issue by AbdalaMask** [dathlin/HslCommunication#41]
hi modbus tcp and rtu  eroor to write

**Comment by Yangjunfengx** [comment]
UPdata to 6.21

**Comment by dathlin** [comment]
v6.2.1 also has error?

**Comment by AbdalaMask** [comment]
The error exists in the release v6.2.1

**Comment by dathlin** [comment]
got it

**Comment by AbdalaMask** [comment]
A message is given that it has been written but has not already been written

**Comment by dathlin** [comment]
i just fix it, and passed unit test

**Comment by AbdalaMask** [comment]
OK

**Comment by AbdalaMask** [comment]
good
