### ISSUE TITLE
关于西门子PLC读写速度的问题，

### ISSUE THREAD

**Issue by wangxing0734** [dathlin/HslCommunication#48]
西门子PLC在响应读写命令的时候，一个周期只能处理一次，假设你要读取100个地址的数据，我们目前这个项目上，只是单独的运行了100次命令，但是这样刷新的速度回非常的慢，OPC的操作是将这个100个地址先整合起来，分几个命令发送，这样读写的速度大大提高，可以参考下

**Comment by dathlin** [comment]
其实本dll也支持批量读取的，只是整合需要自己来处理，另外一次可以进行19个地址的交互，但是自动整合这块代码上不太好操作。需要在看看
