### ISSUE TITLE
使用HslCommunication/TestProject/ComplexNetServer/FormServer.cs 例子代码

### ISSUE THREAD

**Issue by guowushi** [dathlin/HslCommunication#5]
使用HslCommunication/TestProject/ComplexNetServer/FormServer.cs 例子代码，客户端用卓岚TCP调试工具，连接上去后发现马上断开连接。什么原因？

[信息] 2018-07-05 07:41:18.477 thread:[10] NetComplexServer : 启动引擎
[警告] 2018-07-05 07:42:14.028 thread:[25] NetComplexServer : Wait Time Out : 10000
[致命] 2018-07-05 07:42:14.036 thread:[28] NetComplexServer : 错误消息：无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。
源：System
堆栈：   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 HslCommunication.Core.Net.NetworkBase.ReceiveCallback(IAsyncResult ar)
错误类型：System.ObjectDisposedException
调用方法：Int32 EndReceive(System.IAsyncResult, System.Net.Sockets.SocketError ByRef)

**Comment by dathlin** [comment]
因为这个服务器在客户端连接上之后，需要发送一串指令数据，服务器接收不到信息就把客户端踢下线了

**Comment by PeachT** [comment]
什么意思可以清楚吗？

**Comment by dathlin** [comment]
相当于，你的socket连接到这个服务器后，还需要发送一串注册码，向服务器注册信息，注册码格式需要遵循内置的协议，为32字节长度的消息头+客户端的昵称，消息头还包含了令牌信息，所有的都正确了后，才能算注册成功。
