### ISSUE TITLE
怎么读取InputRegister的值

### ISSUE THREAD

**Issue by jiaxiang8756** [dathlin/HslCommunication#6]
如题。我看了源代码ModbusInfo.cs中是有       
        /// <summary>
        /// 读取输入寄存器
        /// </summary>
        public const byte ReadInputRegister = 0x04;
这个值的，但是我发现在所有读取的方法中并没有引用，请问如何读取InputRegister 呢

**Comment by jiaxiang8756** [comment]
我的列子是TCP客户端

**Comment by dathlin** [comment]
这个地址采用富地址的方式实现的，比如你要读取InputRegister地址100的数据，只要地址写成"x=4;100"即可以，适用于所有的Read方法和Write方法
`
OperateResult<short> read = modbus.ReadInt16("x=4;100").Content;
`

**Comment by jiaxiang8756** [comment]
好的，谢谢
