### ISSUE TITLE
读取失败

### ISSUE THREAD

**Issue by jiaxiang8756** [dathlin/HslCommunication#7]
遇到个问题，我读取功能码为03 地址为000的 plc，plc用的是modbus tcp，我读取这个值的时候 isSuccess是false，但是read.content是有值的，值也是正确的。

**Comment by jiaxiang8756** [comment]
var read = busTcpClient.ReadInt16("00021", 1); 

就这一句，read.IsSuccess 的值为false ,read.Content[0]的值为9  
这种情况出现了2次。不是每次都是

**Comment by dathlin** [comment]
后面的1不用带的，你这样是读数组了，数组的读取还没有严格的测试，去掉再试试看
