### ISSUE TITLE
歐姆龍 Fins UDP 無法工作

### ISSUE THREAD

**Issue by acer1204** [dathlin/HslCommunication#79]
我使用的設備是CJ2MCPU31
Fins TCP正常工作
Fins UDP無法工作
寫入指令提示成功 但是數值沒有改變
讀取指令提示成功 但是數值錯誤，都會是1或者是奇怪的數字

**Comment by dathlin** [comment]
你的端口开了tcp，使用udp的网络配置要重新弄的。

**Comment by acer1204** [comment]
預設不是tcp跟udp都是9600開啟？

**Comment by acer1204** [comment]
> 你的端口开了tcp，使用udp的网络配置要重新弄的。
預設不是tcp跟udp都是9600開啟？

![image](https://user-images.githubusercontent.com/6522774/60632936-ee035b80-9e3a-11e9-9576-bd0fa4e4f377.png)
![image](https://user-images.githubusercontent.com/6522774/60632942-f6f42d00-9e3a-11e9-8943-29845915b4b3.png)

**Comment by dathlin** [comment]
按道理说，同一端口的信息，要么tcp要么udp的

**Comment by acer1204** [comment]
> 你的端口开了tcp，使用udp的网络配置要重新弄的。



> 按道理说，同一端口的信息，要么tcp要么udp的

**Comment by acer1204** [comment]
> 按道理说，同一端口的信息，要么tcp要么udp的

我有詢問原廠，原廠說預設是2個都開啟的

但他也不知道為什麼會跳出 21 08的 Error Code

![image](https://user-images.githubusercontent.com/6522774/60694648-5de41580-9f11-11e9-9387-2a6165d8bb60.png)

不可寫入? 但我指令是送讀取D100...

**Comment by dathlin** [comment]
需要再看看
