### ISSUE TITLE
通讯问题

### ISSUE THREAD

**Issue by jiaxiang8756** [dathlin/HslCommunication#8]
大神，最近又遇到个奇怪问题，项目在vs中点击调试运行，可以正确连接modbus 设备，通讯也是没有问题，但是我生成项目后，直接运行bin里面的可执行文件会发现读取的值都为0

**Comment by dathlin** [comment]
一般都是没问题的，你需要不停的打印日志来调试了。

**Comment by jiaxiang8756** [comment]
问题找到了，代码是  有10台设备
`foreach(var t in device)
 {
   t.connect();
}`
这样在VS调试情况下不会有问题，但是直接运行就会读取不到值，有时会连接错误，改成
`
foreach(var t in device)
 {
   t.connect();
   Thread.sleep(500);
}
`
就可以了。
