### ISSUE TITLE
都是读写，为啥不用接口

### ISSUE THREAD

**Issue by nm-1216** [dathlin/HslCommunication#80]
都是读写，为啥不用接口。
![WechatIMG100](https://user-images.githubusercontent.com/16759471/60785125-59736300-a184-11e9-8f7e-6db73ca5ac11.jpeg)
![WechatIMG101](https://user-images.githubusercontent.com/16759471/60785128-5aa49000-a184-11e9-93ac-a41afd004527.jpeg)

**Comment by dathlin** [comment]
好思路，我有一个接口 IReadWriteNet ，所有的plc都实现了这个接口，你上面的工厂模式，单例模式都是偏实际业务的，我还需要想想。

**Comment by nm-1216** [comment]
<img width="666" alt="PLC" src="https://user-images.githubusercontent.com/16759471/61509652-23ef3500-aa22-11e9-8810-5d90e029a950.png">
我的 IPLC 继承了你的IReadWriteNet，加了一些事件。
工厂模式用了 JSON 对地址表的配置，地址表可以取一些别名，别名读写，经常碰见PLC地址变化，可业务都写完了，除非定义全部变了 一一对应地址
